### ISSUE TITLE
errors not notified on the authreqissuer of the SP

### ISSUE THREAD

**Issue by olberger** [bblfish/clerezza#1]
Hi.

I'm testing  foafssl.org as an IdP for my local SP running on a VM.

I testedand was redirected to my SP's URL : https://vm2.localdomain/plugins/authwebid/?error=nocert 
although the IdP was accessed with 
https://foafssl.org/srv/idp?authreqissuer=https://vm2.localdomain/plugins/authwebid/post-login.php

I'd suspect a bug here, as I'd expect the errors or success being notified to the callback provided via authreqissuer.

Thanks in advance.

**Comment by bblfish** [comment]
Thanks for reporting this.

Did you click the "Test" tab at the top, to see if there is a problem with your certificate or foaf file?

**Comment by olberger** [comment]
Yes, there was : the modulus was missing somehow from the RDF, thanks for the suggestion.

**Comment by bblfish** [comment]
Ah cool. Exactly what that test suite is designed for. :-) That's something we are working on improving in the WebID XG btw, so that machines can test endpoints using the machine readable test suite.

**Comment by olberger** [comment]
Have you deployed the fix on foafssl.org ? I'm still not redirected to authwebid/post-login.php?webid=... but to https://vm2.localdomain/plugins/authwebid/?webid=...

Or you only fixed it for the error return and not for success return ?

**Comment by bblfish** [comment]
I did not run my update correctly on the foafssl server and must have tested it on my localhost running instance by mistake yesterday evening. It's running now.

(this is a different bug by the way)
